[2024-12-06T05:04:05.086+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T05:04:05.287+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.create_noncurr_table manual__2024-12-06T05:02:30.153018+00:00 [queued]>
[2024-12-06T05:04:05.302+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.create_noncurr_table manual__2024-12-06T05:02:30.153018+00:00 [queued]>
[2024-12-06T05:04:05.303+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-06T05:04:05.334+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_noncurr_table> on 2024-12-06 05:02:30.153018+00:00
[2024-12-06T05:04:05.351+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2662) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T05:04:05.354+0000] {standard_task_runner.py:72} INFO - Started process 2665 to run task
[2024-12-06T05:04:05.354+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'create_noncurr_table', 'manual__2024-12-06T05:02:30.153018+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmppntgdd2x']
[2024-12-06T05:04:05.356+0000] {standard_task_runner.py:105} INFO - Job 604: Subtask create_noncurr_table
[2024-12-06T05:04:05.466+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.create_noncurr_table manual__2024-12-06T05:02:30.153018+00:00 [running]> on host 9ed27289a118
[2024-12-06T05:04:05.616+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='create_noncurr_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T05:02:30.153018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T05:02:30.153018+00:00'
[2024-12-06T05:04:05.617+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-06T05:04:05.618+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-06T05:04:05.619+0000] {logging_mixin.py:190} INFO - Current task name:create_noncurr_table state:running start_date:2024-12-06 05:04:05.288106+00:00
[2024-12-06T05:04:05.619+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2024-12-06T05:04:05.620+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T05:04:05.621+0000] {sql.py:278} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS NonCurr (
                PPE DECIMAL PRIMARY KEY,
                Intangibles DECIMAL NOT NULL,
                Investments DECIMAL NOT NULL,
                OtherNonCurrentAssets DECIMAL NOT NULL,
                Company VARCHAR(255) NOT NULL
            );
        
[2024-12-06T05:04:05.632+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-06T05:04:05.645+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-06T05:04:05.653+0000] {sql.py:544} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS NonCurr (
                PPE DECIMAL PRIMARY KEY,
                Intangibles DECIMAL NOT NULL,
                Investments DECIMAL NOT NULL,
                OtherNonCurrentAssets DECIMAL NOT NULL,
                Company VARCHAR(255) NOT NULL
            );
        , parameters: None
[2024-12-06T05:04:05.691+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(noncurr, 2200) already exists.

[2024-12-06T05:04:05.712+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-06T05:04:05.713+0000] {logging_mixin.py:190} INFO - Task start:2024-12-06 05:04:05.288106+00:00 end:2024-12-06 05:04:05.711906+00:00 duration:0.4238
[2024-12-06T05:04:05.714+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_noncurr_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2024-12-06 05:02:30.153018+00:00: manual__2024-12-06T05:02:30.153018+00:00, state:running, queued_at: 2024-12-06 05:02:30.432509+00:00. externally triggered: True>
[2024-12-06T05:04:05.715+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(noncurr, 2200) already exists.
[2024-12-06T05:04:05.716+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=create_noncurr_table, run_id=manual__2024-12-06T05:02:30.153018+00:00, execution_date=20241206T050230, start_date=20241206T050405, end_date=20241206T050405
[2024-12-06T05:04:05.737+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T05:04:05.738+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 604 for task create_noncurr_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(noncurr, 2200) already exists.
; 2665)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(noncurr, 2200) already exists.

[2024-12-06T05:04:05.775+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T05:04:05.815+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T05:04:05.819+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
