[2024-12-06T05:03:12.863+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T05:03:20.998+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_stacked_table manual__2024-12-06T05:02:30.153018+00:00 [queued]>
[2024-12-06T05:03:21.658+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v02.insert_into_stacked_table manual__2024-12-06T05:02:30.153018+00:00 [queued]>
[2024-12-06T05:03:21.669+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-06T05:03:22.481+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): insert_into_stacked_table> on 2024-12-06 05:02:30.153018+00:00
[2024-12-06T05:03:23.527+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'insert_into_stacked_table', 'manual__2024-12-06T05:02:30.153018+00:00', '--job-id', '581', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpiwhq1mc2']
[2024-12-06T05:03:23.559+0000] {standard_task_runner.py:105} INFO - Job 581: Subtask insert_into_stacked_table
[2024-12-06T05:03:23.562+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2547) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T05:03:23.578+0000] {standard_task_runner.py:72} INFO - Started process 2600 to run task
[2024-12-06T05:03:25.008+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.insert_into_stacked_table manual__2024-12-06T05:02:30.153018+00:00 [running]> on host 9ed27289a118
[2024-12-06T05:03:26.112+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v02' AIRFLOW_CTX_TASK_ID='insert_into_stacked_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T05:02:30.153018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T05:02:30.153018+00:00'
[2024-12-06T05:03:26.129+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-06T05:03:26.144+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-06T05:03:26.154+0000] {logging_mixin.py:190} INFO - Current task name:insert_into_stacked_table state:running start_date:2024-12-06 05:03:21.106435+00:00
[2024-12-06T05:03:26.181+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator_v02 and current dag run status:running
[2024-12-06T05:03:26.199+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T05:03:26.272+0000] {sql.py:278} INFO - Executing: 
            INSERT INTO Stacked (CostofRevenue,Year, OperatingExpense, ResearchandDevelopment, SGA, Company)
            VALUES
                (52232000000.0, 2021, 5107000000.0, 7575000000.0, 171008000000.0, 'Microsoft'),
                (62650000000.0, 2022, 5900000000.0, 7575000000.0, 171008000000.0, 'Microsoft'),
                (65863000000.0, 2023, 7575000000.0, 7575000000.0, 171008000000.0, 'Microsoft'),
                (74114000000.0, 2024, 7609000000.0, 7609000000.0, 171008000000.0, 'Microsoft');
        
[2024-12-06T05:03:26.650+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-06T05:03:26.992+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-12-06T05:03:27.048+0000] {sql.py:544} INFO - Running statement: 
            INSERT INTO Stacked (CostofRevenue,Year, OperatingExpense, ResearchandDevelopment, SGA, Company)
            VALUES
                (52232000000.0, 2021, 5107000000.0, 7575000000.0, 171008000000.0, 'Microsoft'),
                (62650000000.0, 2022, 5900000000.0, 7575000000.0, 171008000000.0, 'Microsoft'),
                (65863000000.0, 2023, 7575000000.0, 7575000000.0, 171008000000.0, 'Microsoft'),
                (74114000000.0, 2024, 7609000000.0, 7609000000.0, 171008000000.0, 'Microsoft');
        , parameters: None
[2024-12-06T05:03:27.069+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "stacked" does not exist
LINE 2:             INSERT INTO Stacked (CostofRevenue,Year, Operati...
                                ^

[2024-12-06T05:03:27.249+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-06T05:03:27.265+0000] {logging_mixin.py:190} INFO - Task start:2024-12-06 05:03:21.106435+00:00 end:2024-12-06 05:03:27.247713+00:00 duration:6.141278
[2024-12-06T05:03:27.281+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): insert_into_stacked_table> dag:<DAG: dag_with_postgres_operator_v02> dagrun:<DagRun dag_with_postgres_operator_v02 @ 2024-12-06 05:02:30.153018+00:00: manual__2024-12-06T05:02:30.153018+00:00, state:running, queued_at: 2024-12-06 05:02:30.432509+00:00. externally triggered: True>
[2024-12-06T05:03:27.290+0000] {logging_mixin.py:190} INFO - Failure caused by relation "stacked" does not exist
LINE 2:             INSERT INTO Stacked (CostofRevenue,Year, Operati...
                                ^
[2024-12-06T05:03:27.297+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v02, task_id=insert_into_stacked_table, run_id=manual__2024-12-06T05:02:30.153018+00:00, execution_date=20241206T050230, start_date=20241206T050321, end_date=20241206T050327
[2024-12-06T05:03:27.460+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T05:03:27.474+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 581 for task insert_into_stacked_table (relation "stacked" does not exist
LINE 2:             INSERT INTO Stacked (CostofRevenue,Year, Operati...
                                ^
; 2600)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 284, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 489, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 549, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "stacked" does not exist
LINE 2:             INSERT INTO Stacked (CostofRevenue,Year, Operati...
                                ^

[2024-12-06T05:03:27.524+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-06T05:03:27.611+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
